### ISSUE TITLE
Copy resources if lessons not built in situ

### ISSUE THREAD

**Issue by scottfurry** [Twinklebear/TwinklebearDev-Lessons#10]
I've run into situations where building a project in the same folder as the source is not practical. What I have found to be the best practice is to make a separate directory and invoke all necessary build commands in that folder. Clean up then becomes a matter of removing the created directory. This is especially useful when wanting to refresh/reset CMake's cache values.

However, current project do not allow for this practice. The resources folder `res` would have to be manually copied over. I only discovered that by accident and digging. Others may not be so savvy.

To allow for alternate build location, I would like to suggest the code below be appended to the end of the CMakeLists.txt file at directory root right after the line `add_subdirectory(Lesson6)`:

```
if ( NOT ${PROJECT_SOURCE_DIR} STREQUAL ${CMAKE_CURRENT_BINARY_DIR})
    file(COPY "${PROJECT_SOURCE_DIR}/res" DESTINATION "${CMAKE_CURRENT_BINARY_DIR}")
endif()
```

CMake `file(COPY...)` command will do the heavy lifting to copy the directory from source to destination. The `if` statement is there to prevent overwriting the `res` directory if in-place build is being done.

**Comment by Twinklebear** [comment]
I agree, this would make it easier to run the application and remove dependence on some hard-coded paths dependent on the overall project structure. I've got this on my todo list.

**Comment by Twinklebear** [comment]
This is done in d5d1caa377a80c41a72cf41cf39ec79279e34b4c
