### ISSUE TITLE
I know I'm pedantic, but I'm a programmer...

### ISSUE THREAD

**Issue by TomerShech** [Twinklebear/TwinklebearDev-Lessons#15]
In the 1st paragraph of lesson 4, you wrote:
> To read events SDL provides the SDL_Event structure

`SDL_Event` is actually a union, not a struct.
Would you like to fix it, 7 years later? haha

**Comment by Twinklebear** [comment]
Haha you're right! Good catch, I fixed this in https://github.com/Twinklebear/Twinklebear.github.io-jekyll/commit/a1a276c8e40348e1f250f03e86cceb8e3b6f93aa
