### ISSUE TITLE
Lesson 0 crashes on Visual Studio

### ISSUE THREAD

**Issue by Markvy** [Twinklebear/TwinklebearDev-Lessons#16]
After following the steps for setting up SDL in Visual Studio, I'm able to build the executable but when I run it fails with a message saying it can't find SDL2.dll

**Comment by Green-Sky** [comment]
You have to copy the SDL2.dll from the library setup to where the compiled exe is.

**Comment by Markvy** [comment]
Thanks!  Do you figure it makes sense to mention this somewhere in the tutorial?

**Comment by Twinklebear** [comment]
Good to hear it's working! The need to copy SDL2.dll over is mentioned in the Visual Studio tutorial for Windows when discussing [the test program](https://www.willusher.io/sdl2%20tutorials/2013/08/15/lesson-0-visual-studio#the-test-program), the wording could maybe be polished a bit there

**Comment by Markvy** [comment]
Wording is actually fine I think; I somehow managed to skip that entire sentence.  My bad.  Thanks again!

**Comment by Green-Sky** [comment]
Not sure if @Twinklebear is willing to revisit the windows setup but, I'm now used to setting up SDL via vcpkg and the cmake toolchain file. VS19 + cmake does the setup automatically even.

**Comment by Twinklebear** [comment]
vpckg would be cool to add some discusion of to the tutorial, the current setup modes for windows a pre-vcpkg.
