### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Eltii** [Twinklebear/TwinklebearDev-Lessons#6]
without a license we are not even allowed to run or copy your code :(( its all rights reserved for u ,
u should consider adding one ( Public Domain, MIT, ...... )

**Comment by Twinklebear** [comment]
The code is MIT licensed, please see [the license](https://github.com/Twinklebear/TwinklebearDev-Lessons/blob/master/LICENSE.md)

**Comment by Eltii** [comment]
oh Sorry .... didnt see that
u should also put it in the website .
